name: $PROJ-$ENV-$ENV_UNIT
services:
  account:
    image: $PROJ-$APP:$VERSION-$ENV
    entrypoint: "/usr/local/bin/supervisord"
    command: ["-c", "/etc/supervisord.conf"]
    env_file: "./$ENV-$ENV_UNIT-app.env"
    depends_on:
      - mysql
    configs:
      - source: account-supervisord-conf
        target: /etc/supervisord.conf
      - source: account-mysql-conf
        target: /opt/twp/account/conf/mysql.yml
      - source: account-app-conf
        target: /opt/twp/account/conf/app.yml
    volumes:
      - account-log:/opt/twp/account/log
      - ./src:/opt/twp/account/src
    networks:
      account-subnet:
        ipv4_address: ${ACCOUNT_NODE_01_IP}
      mysql-external-subnet:
configs:
  account-supervisord-conf:
    file: ./config/supervisord.conf
  account-mysql-conf:
    file: ./config/mysql.yml
  account-app-conf:
    file: ./config/app.yml
volumes:
  account-log:
    driver: local
networks:
  account-subnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${ACCOUNT_SUBNET_IP_RANGES}
  mysql-external-subnet:
    name: $PROJ-$ENV-${ENV_UNIT}_mysql-subnet
    external: true
